### ISSUE TITLE
根据邮箱获取open_id接口报错，{ code: 10004, msg: 'user not found' }

### ISSUE THREAD

**Issue by leokang28** [larksuite/oapi-sdk-nodejs#12]
nodejs sdk @byted-service/lark@2.4.2下getIdsByEmailV4接口，取已离职的人的open_id会报这个错误，客服同学反馈说是sdk这边的bug

**Comment by zhaoche27** [comment]
这个sdk不是飞书开放平台这边维护的，请联系这个包的开发者。 推荐使用 larksuite/oapi-sdk-nodejs。
