### ISSUE TITLE
貌似不支持飞书最新的IM api？

### ISSUE THREAD

**Issue by Bubbleinpit** [larksuite/oapi-sdk-nodejs#15]
例如发送消息 https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/create
以及接受消息的事件：https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/events/receive

**Comment by Bubbleinpit** [comment]
个人失误，没有添加权限订阅事件，请无视

**Comment by LeoQuote** [comment]
这个是真的呀, 还在用老api, 也不知道怎么指定 queryparameter

**Comment by zhaoche27** [comment]
看看 README 文档

![Uploading image.png…]()

**Comment by LeoQuote** [comment]
感谢, 我也刚看到, 实例可以改一下用新的接口了
