### ISSUE TITLE
多config根据app_id自动选择相应的config

### ISSUE THREAD

**Issue by Bubbleinpit** [larksuite/oapi-sdk-nodejs#16]
这样做可以满足一套代码与环境适配多个租户的相同机器人。

最近在开发机器人，需要在测试租户测试，发现httpHandle调用的时候必须手动传入config，不能根据事件订阅的event.header.app_id自动识别该使用哪一个config。

这个需求可以考虑一下不？

**Comment by Bubbleinpit** [comment]
因为现在sdk其实已经满足多config的事件订阅，lark.event.setTypeHandler可以绑定多个config，但调用的时候还需要手动指定有点麻烦。主要是我使用了数据加密，如果要自己判断使用那个config还得先解密，那就跟sdk里的unmarshalFunc做的工作重复了，解密两次没必要。。

**Comment by Bubbleinpit** [comment]
目前我个人的解决方案是解密自己做，根据app_id判断使用哪个config，然后调用event.httpHandle的时候，传入解密的数据并且config中不传入encryptKey

**Comment by zhaoche27** [comment]
【lark.event.setTypeHandler可以绑定多个config，但调用的时候还需要手动指定有点麻烦】  读取的你的许多app配置，然后 for 循环不行吗。

**Comment by Bubbleinpit** [comment]
> 读取的你的许多app配置，然后 for 循环不行吗。

@zhaoche27 可以呀，但是这样会导致那些本来不需要调用的handler被调用了，虽然可以在handler里判断app_id来确定是否执行业务逻辑，但解密数据这个操作是多余的。
