### ISSUE TITLE
core.api.request http header  不可以自定义

### ISSUE THREAD

**Issue by KevinGong2013** [larksuite/oapi-sdk-nodejs#20]
https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-members/delete

比如这个接口，http method 为 ‘DELETE’, 不会自动设置 content-type:application/json; charset=utf-8, 也没有接口可以设置。

**Comment by zhaoche27** [comment]
没有请求体的情况下，是没有content-type的。

![image](https://user-images.githubusercontent.com/5029131/148023828-c38dc2df-cf67-49a9-8ca6-8eaaa839f1f9.png)

![image](https://user-images.githubusercontent.com/5029131/148023788-216ef485-1628-456c-99b6-cc69e8f32afc.png)

**Comment by KevinGong2013** [comment]
知道问题所在了。

这个api 的http method 应该好似delete，我写成post了，
然后服务端报错为 content-type 不对。我仔细检查。。
