### ISSUE TITLE
bot/v3/info 返回没有bot字段

### ISSUE THREAD

**Issue by Emptymu** [larksuite/oapi-sdk-nodejs#25]
使用@larksuiteoapi/allcore调用bot/v3/info后返回响应体没有bot字段

<img width="295" alt="20220214-152208" src="https://user-images.githubusercontent.com/25358596/153817993-5582a2d5-980f-4ed1-870f-1bb55bc78c96.png">

**Comment by zhaoche27** [comment]
升级一下 SDK

**Comment by Emptymu** [comment]
> 升级一下 SDK

This worked! Thanks
