### ISSUE TITLE
lark.core.DefaultStore()的expire单位是毫秒，但access_token的expire单位是秒，导致无效缓存

### ISSUE THREAD

**Issue by dingXX** [larksuite/oapi-sdk-nodejs#8]
@larksuiteoapi/allcore@1.0.7
readme示例中的的store方法是用的 `new lark.core.DefaultStore()` ，但看`DefaultStore`的缓存机制的expire的单位是ms的
而在使用侧缓存access_token时，是[直接将token的exipire（单位s）作为参数](https://github.com/larksuite/oapi-sdk-nodejs/blob/f0efe7ded5fe29619b07f45a2149c0f8b7407fb6/packages/api/src/core/handlers/accessToken.ts#L76)传给了store ，这导致了如果直接使用 `new lark.core.DefaultStore()`时，没法做到缓存效果，两者的expire字段单温是否能保持一致？

**Comment by zhaoche27** [comment]
谢谢反馈，已经修复。 1.0.10 版本
